// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: src/protos/product.proto

package grpc_server1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductRPCClient is the client API for ProductRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductRPCClient interface {
	ProductsRPC(ctx context.Context, in *User, opts ...grpc.CallOption) (*Products, error)
	SingelProduct(ctx context.Context, in *RequestProduct, opts ...grpc.CallOption) (*Product, error)
}

type productRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewProductRPCClient(cc grpc.ClientConnInterface) ProductRPCClient {
	return &productRPCClient{cc}
}

func (c *productRPCClient) ProductsRPC(ctx context.Context, in *User, opts ...grpc.CallOption) (*Products, error) {
	out := new(Products)
	err := c.cc.Invoke(ctx, "/protos.ProductRPC/ProductsRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productRPCClient) SingelProduct(ctx context.Context, in *RequestProduct, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/protos.ProductRPC/SingelProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductRPCServer is the server API for ProductRPC service.
// All implementations must embed UnimplementedProductRPCServer
// for forward compatibility
type ProductRPCServer interface {
	ProductsRPC(context.Context, *User) (*Products, error)
	SingelProduct(context.Context, *RequestProduct) (*Product, error)
	mustEmbedUnimplementedProductRPCServer()
}

// UnimplementedProductRPCServer must be embedded to have forward compatible implementations.
type UnimplementedProductRPCServer struct {
}

func (UnimplementedProductRPCServer) ProductsRPC(context.Context, *User) (*Products, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProductsRPC not implemented")
}
func (UnimplementedProductRPCServer) SingelProduct(context.Context, *RequestProduct) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SingelProduct not implemented")
}
func (UnimplementedProductRPCServer) mustEmbedUnimplementedProductRPCServer() {}

// UnsafeProductRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductRPCServer will
// result in compilation errors.
type UnsafeProductRPCServer interface {
	mustEmbedUnimplementedProductRPCServer()
}

func RegisterProductRPCServer(s grpc.ServiceRegistrar, srv ProductRPCServer) {
	s.RegisterService(&ProductRPC_ServiceDesc, srv)
}

func _ProductRPC_ProductsRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRPCServer).ProductsRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ProductRPC/ProductsRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRPCServer).ProductsRPC(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductRPC_SingelProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestProduct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRPCServer).SingelProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ProductRPC/SingelProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRPCServer).SingelProduct(ctx, req.(*RequestProduct))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductRPC_ServiceDesc is the grpc.ServiceDesc for ProductRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ProductRPC",
	HandlerType: (*ProductRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProductsRPC",
			Handler:    _ProductRPC_ProductsRPC_Handler,
		},
		{
			MethodName: "SingelProduct",
			Handler:    _ProductRPC_SingelProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/protos/product.proto",
}
