// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: src/protos/user.proto

package grpc_server1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// request
type DataSelectUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DataSelectUser) Reset() {
	*x = DataSelectUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protos_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataSelectUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSelectUser) ProtoMessage() {}

func (x *DataSelectUser) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSelectUser.ProtoReflect.Descriptor instead.
func (*DataSelectUser) Descriptor() ([]byte, []int) {
	return file_src_protos_user_proto_rawDescGZIP(), []int{0}
}

func (x *DataSelectUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DataSelectUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *DataSelectUsers) Reset() {
	*x = DataSelectUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protos_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataSelectUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSelectUsers) ProtoMessage() {}

func (x *DataSelectUsers) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSelectUsers.ProtoReflect.Descriptor instead.
func (*DataSelectUsers) Descriptor() ([]byte, []int) {
	return file_src_protos_user_proto_rawDescGZIP(), []int{1}
}

func (x *DataSelectUsers) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// response
type ResponseSelectUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string     `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEmail   string     `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	UserName    string     `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserImage   string     `protobuf:"bytes,4,opt,name=user_image,json=userImage,proto3" json:"user_image,omitempty"`
	UserStatus  string     `protobuf:"bytes,5,opt,name=user_status,json=userStatus,proto3" json:"user_status,omitempty"`
	CreatedDate string     `protobuf:"bytes,6,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	LastUpdate  string     `protobuf:"bytes,7,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	Products    []*Product `protobuf:"bytes,8,rep,name=Products,proto3" json:"Products,omitempty"`
}

func (x *ResponseSelectUser) Reset() {
	*x = ResponseSelectUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protos_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseSelectUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseSelectUser) ProtoMessage() {}

func (x *ResponseSelectUser) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseSelectUser.ProtoReflect.Descriptor instead.
func (*ResponseSelectUser) Descriptor() ([]byte, []int) {
	return file_src_protos_user_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseSelectUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResponseSelectUser) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *ResponseSelectUser) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ResponseSelectUser) GetUserImage() string {
	if x != nil {
		return x.UserImage
	}
	return ""
}

func (x *ResponseSelectUser) GetUserStatus() string {
	if x != nil {
		return x.UserStatus
	}
	return ""
}

func (x *ResponseSelectUser) GetCreatedDate() string {
	if x != nil {
		return x.CreatedDate
	}
	return ""
}

func (x *ResponseSelectUser) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

func (x *ResponseSelectUser) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type ResponseSelectUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*ResponseSelectUser `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ResponseSelectUsers) Reset() {
	*x = ResponseSelectUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_protos_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseSelectUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseSelectUsers) ProtoMessage() {}

func (x *ResponseSelectUsers) ProtoReflect() protoreflect.Message {
	mi := &file_src_protos_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseSelectUsers.ProtoReflect.Descriptor instead.
func (*ResponseSelectUsers) Descriptor() ([]byte, []int) {
	return file_src_protos_user_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseSelectUsers) GetData() []*ResponseSelectUser {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_src_protos_user_proto protoreflect.FileDescriptor

var file_src_protos_user_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a,
	0x18, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x0e, 0x44, 0x61, 0x74,
	0x61, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x0f, 0x44,
	0x61, 0x74, 0x61, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x22, 0x9a, 0x02, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73,
	0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x73, 0x22, 0x45, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x94, 0x01, 0x0a, 0x07, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x50, 0x43, 0x12, 0x42, 0x0a, 0x0a, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0b, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x22, 0x00, 0x42,
	0x1a, 0x5a, 0x18, 0x67, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x31, 0x3b, 0x67,
	0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_src_protos_user_proto_rawDescOnce sync.Once
	file_src_protos_user_proto_rawDescData = file_src_protos_user_proto_rawDesc
)

func file_src_protos_user_proto_rawDescGZIP() []byte {
	file_src_protos_user_proto_rawDescOnce.Do(func() {
		file_src_protos_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_protos_user_proto_rawDescData)
	})
	return file_src_protos_user_proto_rawDescData
}

var file_src_protos_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_src_protos_user_proto_goTypes = []interface{}{
	(*DataSelectUser)(nil),      // 0: protos.DataSelectUser
	(*DataSelectUsers)(nil),     // 1: protos.DataSelectUsers
	(*ResponseSelectUser)(nil),  // 2: protos.ResponseSelectUser
	(*ResponseSelectUsers)(nil), // 3: protos.ResponseSelectUsers
	(*Product)(nil),             // 4: protos.Product
}
var file_src_protos_user_proto_depIdxs = []int32{
	4, // 0: protos.ResponseSelectUser.Products:type_name -> protos.Product
	2, // 1: protos.ResponseSelectUsers.data:type_name -> protos.ResponseSelectUser
	0, // 2: protos.UserRPC.SelectUser:input_type -> protos.DataSelectUser
	1, // 3: protos.UserRPC.SelectUsers:input_type -> protos.DataSelectUsers
	2, // 4: protos.UserRPC.SelectUser:output_type -> protos.ResponseSelectUser
	3, // 5: protos.UserRPC.SelectUsers:output_type -> protos.ResponseSelectUsers
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_protos_user_proto_init() }
func file_src_protos_user_proto_init() {
	if File_src_protos_user_proto != nil {
		return
	}
	file_src_protos_product_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_src_protos_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataSelectUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protos_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataSelectUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protos_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseSelectUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_protos_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseSelectUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_protos_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_protos_user_proto_goTypes,
		DependencyIndexes: file_src_protos_user_proto_depIdxs,
		MessageInfos:      file_src_protos_user_proto_msgTypes,
	}.Build()
	File_src_protos_user_proto = out.File
	file_src_protos_user_proto_rawDesc = nil
	file_src_protos_user_proto_goTypes = nil
	file_src_protos_user_proto_depIdxs = nil
}
